version: '3.12'
services:
  web:
    build: .
    # command: bash -c "cd openduck-py && python setup.py develop && aws s3 cp --recursive s3://uberduck-models-us-west-2/prototype models && uvicorn openduck_py.routers.main:app --reload --host 0.0.0.0 --port 8000"
    # command: bash -c "cd openduck-py && python setup.py develop && uvicorn openduck_py.admin.main:app --reload --host 0.0.0.0 --port 8000"
    command: bash -c "cd openduck-py && python setup.py develop && gunicorn openduck_py.admin.main:app --reload --bind 0.0.0.0:8001 --timeout 120 --log-level debug"
    working_dir: /openduck-py
    volumes:
      - .:/openduck-py
    ports:
      - "8000:8000"
      - "8001:8001"
    env_file:
      - .env.dev
    runtime: nvidia
