version: '3.12'
services:
  web:
    build: .
    command: bash -c "cd openduck-py && python setup.py develop && aws s3 cp --recursive s3://uberduck-models-us-west-2/prototype models && uvicorn openduck_py.routers.main:app --reload --host 0.0.0.0 --port 8000"
    working_dir: /openduck-py
    volumes:
      - .:/openduck-py
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
