"""initial_migration

Revision ID: 00cad591e71a
Revises: 
Create Date: 2024-02-12 22:14:42.765988+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "00cad591e71a"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audio",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_audio_user_id"), "audio", ["user_id"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("propel_auth_id", sa.Text(), nullable=True),
        sa.Column("username", sa.Text(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("is_admin", sa.Boolean(), nullable=True),
        sa.Column("stripe_customer_id", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("propel_auth_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        op.f("ix_user_stripe_customer_id"), "user", ["stripe_customer_id"], unique=False
    )
    op.create_table(
        "ml_model",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("uuid", sa.Text(), nullable=False),
        sa.Column("model_type", sa.Text(), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("config", sqlite.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(op.f("ix_ml_model_user_id"), "ml_model", ["user_id"], unique=False)
    op.create_table(
        "voice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("ml_model_id", sa.BigInteger(), nullable=True),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("voice_uuid", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=True),
        sa.Column("category", sa.Text(), nullable=True),
        sa.Column("model_type", sa.Text(), nullable=True),
        sa.Column("is_private", sa.Boolean(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("language", sa.Text(), nullable=False),
        sa.Column("meta_json", sqlite.JSON(), nullable=True),
        sa.Column("age", sa.Text(), nullable=True),
        sa.Column("gender", sa.Text(), nullable=True),
        sa.Column("accent", sa.Text(), nullable=True),
        sa.Column("mood", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("style", sa.Text(), nullable=True),
        sa.Column("sample_url", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["ml_model_id"], ["ml_model.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("voice_uuid"),
    )
    op.create_index(op.f("ix_voice_accent"), "voice", ["accent"], unique=False)
    op.create_index(op.f("ix_voice_age"), "voice", ["age"], unique=False)
    op.create_index(
        op.f("ix_voice_description"), "voice", ["description"], unique=False
    )
    op.create_index(op.f("ix_voice_gender"), "voice", ["gender"], unique=False)
    op.create_index(op.f("ix_voice_image_url"), "voice", ["image_url"], unique=False)
    op.create_index(op.f("ix_voice_language"), "voice", ["language"], unique=False)
    op.create_index(
        op.f("ix_voice_ml_model_id"), "voice", ["ml_model_id"], unique=False
    )
    op.create_index(op.f("ix_voice_mood"), "voice", ["mood"], unique=False)
    op.create_index(op.f("ix_voice_name"), "voice", ["name"], unique=False)
    op.create_index(op.f("ix_voice_sample_url"), "voice", ["sample_url"], unique=False)
    op.create_index(op.f("ix_voice_style"), "voice", ["style"], unique=False)
    op.create_index(op.f("ix_voice_user_id"), "voice", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_user_id"), table_name="voice")
    op.drop_index(op.f("ix_voice_style"), table_name="voice")
    op.drop_index(op.f("ix_voice_sample_url"), table_name="voice")
    op.drop_index(op.f("ix_voice_name"), table_name="voice")
    op.drop_index(op.f("ix_voice_mood"), table_name="voice")
    op.drop_index(op.f("ix_voice_ml_model_id"), table_name="voice")
    op.drop_index(op.f("ix_voice_language"), table_name="voice")
    op.drop_index(op.f("ix_voice_image_url"), table_name="voice")
    op.drop_index(op.f("ix_voice_gender"), table_name="voice")
    op.drop_index(op.f("ix_voice_description"), table_name="voice")
    op.drop_index(op.f("ix_voice_age"), table_name="voice")
    op.drop_index(op.f("ix_voice_accent"), table_name="voice")
    op.drop_table("voice")
    op.drop_index(op.f("ix_ml_model_user_id"), table_name="ml_model")
    op.drop_table("ml_model")
    op.drop_index(op.f("ix_user_stripe_customer_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_audio_user_id"), table_name="audio")
    op.drop_table("audio")
    # ### end Alembic commands ###
