"""add recording url

Revision ID: 4a8aae996f95
Revises: 6bbc3879a288
Create Date: 2024-04-01 20:10:56.189186+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a8aae996f95'
down_revision: Union[str, None] = '6bbc3879a288'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_history', sa.Column('recording_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_history', 'recording_url')
    # ### end Alembic commands ###
