"""delete_unused_tables

Revision ID: 5d6086543a18
Revises: e0f409cb4d81
Create Date: 2024-03-05 19:59:27.946874+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "5d6086543a18"
down_revision: Union[str, None] = "e0f409cb4d81"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_ml_model_user_id", table_name="ml_model")
    op.drop_table("ml_model")
    op.drop_index("ix_voice_accent", table_name="voice")
    op.drop_index("ix_voice_age", table_name="voice")
    op.drop_index("ix_voice_description", table_name="voice")
    op.drop_index("ix_voice_gender", table_name="voice")
    op.drop_index("ix_voice_image_url", table_name="voice")
    op.drop_index("ix_voice_language", table_name="voice")
    op.drop_index("ix_voice_ml_model_id", table_name="voice")
    op.drop_index("ix_voice_mood", table_name="voice")
    op.drop_index("ix_voice_name", table_name="voice")
    op.drop_index("ix_voice_sample_url", table_name="voice")
    op.drop_index("ix_voice_style", table_name="voice")
    op.drop_index("ix_voice_user_id", table_name="voice")
    op.drop_table("voice")
    op.drop_index("ix_audio_user_id", table_name="audio")
    op.drop_table("audio")
    op.drop_index("ix_user_stripe_customer_id", table_name="user")
    op.drop_table("user")
    op.drop_index(
        "deployment_user_id_url_name_unique_not_deleted",
        table_name="template_deployment",
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_index("ix_template_deployment_id", table_name="template_deployment")
    op.drop_index("ix_template_deployment_url_name", table_name="template_deployment")
    op.drop_index("ix_template_deployment_user_id", table_name="template_deployment")
    op.drop_table("template_deployment")
    op.drop_index("ix_template_prompt_id", table_name="template_prompt")
    op.drop_index("ix_template_prompt_url_name", table_name="template_prompt")
    op.drop_index("ix_template_prompt_user_id", table_name="template_prompt")
    op.drop_index("ix_template_prompt_uuid", table_name="template_prompt")
    op.drop_index(
        "prompt_user_id_url_name_unique_not_deleted",
        table_name="template_prompt",
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.drop_table("template_prompt")
    op.drop_index("ix_chat_history_user_id", table_name="chat_history")
    op.drop_constraint(None, "chat_history", type_="foreignkey")
    op.drop_column("chat_history", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("chat_history", sa.Column("user_id", sa.INTEGER(), nullable=True))
    op.create_foreign_key(
        None, "chat_history", "user", ["user_id"], ["id"], ondelete="CASCADE"
    )
    op.create_index(
        "ix_chat_history_user_id", "chat_history", ["user_id"], unique=False
    )
    op.create_table(
        "template_prompt",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("uuid", sa.TEXT(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("url_name", sa.VARCHAR(), nullable=False),
        sa.Column("display_name", sa.VARCHAR(), nullable=True),
        sa.Column("prompt", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.Column("meta_json", sqlite.JSON(), nullable=True),
        sa.Column("model", sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "prompt_user_id_url_name_unique_not_deleted",
        "template_prompt",
        ["user_id", "url_name"],
        unique=1,
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.create_index("ix_template_prompt_uuid", "template_prompt", ["uuid"], unique=1)
    op.create_index(
        "ix_template_prompt_user_id", "template_prompt", ["user_id"], unique=False
    )
    op.create_index(
        "ix_template_prompt_url_name", "template_prompt", ["url_name"], unique=False
    )
    op.create_index("ix_template_prompt_id", "template_prompt", ["id"], unique=False)
    op.create_table(
        "template_deployment",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("uuid", sa.TEXT(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=False),
        sa.Column("url_name", sa.VARCHAR(), nullable=False),
        sa.Column("display_name", sa.VARCHAR(), nullable=True),
        sa.Column("prompt", sqlite.JSON(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.Column("meta_json", sqlite.JSON(), nullable=True),
        sa.Column("model", sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index(
        "ix_template_deployment_user_id",
        "template_deployment",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_template_deployment_url_name",
        "template_deployment",
        ["url_name"],
        unique=False,
    )
    op.create_index(
        "ix_template_deployment_id", "template_deployment", ["id"], unique=False
    )
    op.create_index(
        "deployment_user_id_url_name_unique_not_deleted",
        "template_deployment",
        ["user_id", "url_name"],
        unique=1,
        sqlite_where=sa.text("deleted_at IS NULL"),
    )
    op.create_table(
        "user",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("propel_auth_id", sa.TEXT(), nullable=True),
        sa.Column("username", sa.TEXT(), nullable=False),
        sa.Column("email", sa.TEXT(), nullable=False),
        sa.Column("is_admin", sa.BOOLEAN(), nullable=True),
        sa.Column("stripe_customer_id", sa.TEXT(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
        sa.UniqueConstraint("propel_auth_id"),
        sa.UniqueConstraint("username"),
    )
    op.create_index(
        "ix_user_stripe_customer_id", "user", ["stripe_customer_id"], unique=False
    )
    op.create_table(
        "audio",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("path", sa.TEXT(), nullable=False),
        sa.Column("uuid", sa.TEXT(), nullable=False),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index("ix_audio_user_id", "audio", ["user_id"], unique=False)
    op.create_table(
        "voice",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("ml_model_id", sa.BIGINT(), nullable=True),
        sa.Column("name", sa.TEXT(), nullable=False),
        sa.Column("voice_uuid", sa.TEXT(), nullable=False),
        sa.Column("display_name", sa.TEXT(), nullable=True),
        sa.Column("category", sa.TEXT(), nullable=True),
        sa.Column("model_type", sa.TEXT(), nullable=True),
        sa.Column("is_private", sa.BOOLEAN(), nullable=True),
        sa.Column("created_at", sa.DATETIME(), nullable=False),
        sa.Column("deleted_at", sa.DATETIME(), nullable=True),
        sa.Column("language", sa.TEXT(), nullable=False),
        sa.Column("meta_json", sqlite.JSON(), nullable=True),
        sa.Column("age", sa.TEXT(), nullable=True),
        sa.Column("gender", sa.TEXT(), nullable=True),
        sa.Column("accent", sa.TEXT(), nullable=True),
        sa.Column("mood", sa.TEXT(), nullable=True),
        sa.Column("description", sa.TEXT(), nullable=True),
        sa.Column("style", sa.TEXT(), nullable=True),
        sa.Column("sample_url", sa.TEXT(), nullable=True),
        sa.Column("image_url", sa.TEXT(), nullable=True),
        sa.ForeignKeyConstraint(["ml_model_id"], ["ml_model.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("voice_uuid"),
    )
    op.create_index("ix_voice_user_id", "voice", ["user_id"], unique=False)
    op.create_index("ix_voice_style", "voice", ["style"], unique=False)
    op.create_index("ix_voice_sample_url", "voice", ["sample_url"], unique=False)
    op.create_index("ix_voice_name", "voice", ["name"], unique=False)
    op.create_index("ix_voice_mood", "voice", ["mood"], unique=False)
    op.create_index("ix_voice_ml_model_id", "voice", ["ml_model_id"], unique=False)
    op.create_index("ix_voice_language", "voice", ["language"], unique=False)
    op.create_index("ix_voice_image_url", "voice", ["image_url"], unique=False)
    op.create_index("ix_voice_gender", "voice", ["gender"], unique=False)
    op.create_index("ix_voice_description", "voice", ["description"], unique=False)
    op.create_index("ix_voice_age", "voice", ["age"], unique=False)
    op.create_index("ix_voice_accent", "voice", ["accent"], unique=False)
    op.create_table(
        "ml_model",
        sa.Column("id", sa.BIGINT(), nullable=False),
        sa.Column("user_id", sa.INTEGER(), nullable=True),
        sa.Column("uuid", sa.TEXT(), nullable=False),
        sa.Column("model_type", sa.TEXT(), nullable=False),
        sa.Column("path", sa.TEXT(), nullable=False),
        sa.Column("config", sqlite.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["user.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("path"),
        sa.UniqueConstraint("uuid"),
    )
    op.create_index("ix_ml_model_user_id", "ml_model", ["user_id"], unique=False)
    # ### end Alembic commands ###
