"""latency_seconds

Revision ID: 6bbc3879a288
Revises: 47f5b8adb56b
Create Date: 2024-03-13 19:06:43.480032+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "6bbc3879a288"
down_revision: Union[str, None] = "47f5b8adb56b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "chat_record", sa.Column("latency_seconds", sa.Float(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("chat_record", "latency_seconds")
    # ### end Alembic commands ###
