"""add_chat_records

Revision ID: f81331801fd7
Revises: c4e71a1a96da
Create Date: 2024-02-27 18:59:36.291728+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'f81331801fd7'
down_revision: Union[str, None] = 'c4e71a1a96da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Text(), nullable=False),
    sa.Column('event_name', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('meta_json', sqlite.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_history.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_record_session_id'), 'chat_record', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_record_session_id'), table_name='chat_record')
    op.drop_table('chat_record')
    # ### end Alembic commands ###
